# Generated by Django 2.2.7 on 2019-12-08 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_management', '0002_auto_20191208_1751'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='课程名')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='简介')),
                ('teach_classes', models.ManyToManyField(to='student_management.ClassGrade')),
                ('teach_courses', models.ManyToManyField(to='teacher.Courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.CreateModel(
            name='LeaderTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management.ClassGrade', verbose_name='负责班级')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
            options={
                'verbose_name': '班主任',
                'verbose_name_plural': '班主任',
            },
        ),
    ]
