# Generated by Django 2.2.7 on 2019-12-08 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('code', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='student_management.Area', verbose_name='上级行政区划')),
            ],
            options={
                'verbose_name': '行政区划',
                'verbose_name_plural': '行政区划',
            },
        ),
        migrations.CreateModel(
            name='ClassGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0701', '7年级01班'), ('0702', '7年级02班'), ('0703', '7年级03班'), ('0704', '7年级04班'), ('0705', '7年级05班'), ('0706', '7年级06班'), ('0707', '7年级07班'), ('0708', '7年级08班'), ('0709', '7年级09班'), ('0710', '7年级10班'), ('0711', '7年级11班'), ('0712', '7年级12班')], max_length=4, verbose_name='班级名称')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=19, verbose_name='学籍号')),
                ('is_under_poverty', models.BooleanField(default=False, verbose_name='是否精准扶贫')),
                ('is_disability', models.BooleanField(default=False, verbose_name='是否残疾')),
                ('address', models.CharField(max_length=100, verbose_name='家庭住址')),
                ('parents_name', models.CharField(max_length=12, verbose_name='监护人')),
                ('contact', models.CharField(max_length=11, verbose_name='联系人电话')),
                ('city', models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='city_addresses', to='student_management.Area', verbose_name='市')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.ClassGrade', verbose_name='班级')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_addresses', to='student_management.Area', verbose_name='乡镇')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_addresses', to='student_management.Area', verbose_name='区/县')),
                ('province', models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='province_addresses', to='student_management.Area', verbose_name='省')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
    ]
