# Generated by Django 2.2.7 on 2019-11-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
    ]
